# Generated by Django 5.2.9 on 2026-01-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('CONTRACTOR', 'Contractor'), ('SUPPORT', 'Support')], db_index=True, default='CUSTOMER', max_length=20),
        ),
    ]
