# Generated by Django 5.2.9 on 2026-01-02 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ASSIGNED', 'Assigned'), ('DONE', 'Done'), ('CANCELED', 'Canceled')], db_index=True, default='OPEN', max_length=10)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('work_reported_done_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_contractor', models.ForeignKey(blank=True, limit_choices_to={'role': 'CONTRACTOR'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ads_assigned', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('WITHDRAWN', 'Withdrawn')], db_index=True, default='APPLIED', max_length=10)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='ads.ad')),
                ('contractor', models.ForeignKey(limit_choices_to={'role': 'CONTRACTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='ad_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['status', 'created_at'], name='ads_ad_status_f0db0f_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['creator', 'created_at'], name='ads_ad_creator_aed909_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['assigned_contractor', 'status'], name='ads_ad_assigne_ea04a9_idx'),
        ),
        migrations.AddConstraint(
            model_name='ad',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['OPEN', 'CANCELED']), ('assigned_contractor__isnull', False), _connector='OR'), name='ad_assignee_required_when_assigned_or_done'),
        ),
        migrations.AddConstraint(
            model_name='ad',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['OPEN', 'ASSIGNED', 'CANCELED']), ('work_reported_done_at__isnull', False), _connector='OR'), name='ad_done_requires_work_reported_done_at'),
        ),
        migrations.AddConstraint(
            model_name='ad',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['OPEN', 'ASSIGNED', 'CANCELED']), ('completed_at__isnull', False), _connector='OR'), name='ad_done_requires_completed_at'),
        ),
        migrations.AddIndex(
            model_name='adrequest',
            index=models.Index(fields=['ad', 'status'], name='ads_adreque_ad_id_c11d9a_idx'),
        ),
        migrations.AddIndex(
            model_name='adrequest',
            index=models.Index(fields=['contractor', 'status'], name='ads_adreque_contrac_7b2598_idx'),
        ),
        migrations.AddConstraint(
            model_name='adrequest',
            constraint=models.UniqueConstraint(fields=('ad', 'contractor'), name='uniq_ad_request_per_contractor'),
        ),
    ]
